spring:
  application:
    name: stream-processor
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    streams:
      application-id: stream-processor
      properties:
        default.timestamp.extractor: com.example.streamprocessor.PlayEventTimestampExtractor
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        commit.interval.ms: 1000

server:
  port: 8081
